# Generated by Django 3.2.10 on 2021-12-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_table_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_no',
            field=models.IntegerField(),
        ),
    ]
