# Generated by Django 3.2.10 on 2021-12-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_table_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], default='InProgress', max_length=10),
        ),
    ]
