# Generated by Django 3.2.10 on 2021-12-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_no',
            field=models.IntegerField(verbose_name='Order No'),
        ),
    ]
